### ISSUE TITLE
glTF.exe returns -1 in vs2013

### ISSUE THREAD

**Issue by Cyperwu** [cyrillef/FBX-glTF#4]
i can't figure out where the problem is. Please help me

**Comment by vijayaprakash** [comment]
Hi,

What are all the command line options you are giving? Could you please elaborate how you are executing the "glTF.exe"?

Thanks,
Vijay.

**Comment by Cyperwu** [comment]
Hi Vijaya,

I was building the solution accroding to the [https://github.com/cyrillef/FBX-glTF#windows](url) in README.md. I didn't use command line and when it comes to step 5, vs2013 returned a -1.

Thanks,
Cyper

**Comment by vijayaprakash** [comment]
Hi, 

Before build the solution, did you install the dependencies ?
1. The Casablanca C++ RESTful SDK - version 2.4.0.1
2. The FBX C++ SDK - version 2015.1

Make sure that the path of FBX SDK is correct in your solution.

Thanks,
Vijay.

**Comment by vijayaprakash** [comment]
Logfile: I am using Visual Studio 2013.

NuGet package restore started.
Restoring NuGet packages for solution C:\glTF\FBX-glTF-master\FBX-glTF-master\glTF.sln.
NuGet Package restored finished for solution C:\glTF\FBX-glTF-master\FBX-glTF-master\glTF.sln.
Restoring NuGet packages for project IO-glTF.
Skipping NuGet package cpprestsdk 2.4.0.1 since it is already installed.
NuGet Package restored finished for project IO-glTF.
Restoring NuGet packages for project glTF.
Skipping NuGet package cpprestsdk 2.4.0.1 since it is already installed.
NuGet Package restored finished for project glTF.
All packages are already installed and there is nothing to restore.
NuGet package restore finished.
1>------ Rebuild All started: Project: IO-glTF, Configuration: Debug x64 ------
2>------ Rebuild All started: Project: glTF, Configuration: Debug x64 ------
1>Build started 21-04-2016 AM 11:51:52.
1>_PrepareForClean:
1>  Deleting file "x64\Debug\IO-glTF.tlog\IO-glTF.lastbuildstate".
2>Build started 21-04-2016 AM 11:51:52.
2>_PrepareForClean:
2>  Deleting file "x64\Debug\glTF.tlog\glTF.lastbuildstate".
1>InitializeBuildStatus:
1>  Touching "x64\Debug\IO-glTF.tlog\unsuccessfulbuild".
2>InitializeBuildStatus:
2>  Touching "x64\Debug\glTF.tlog\unsuccessfulbuild".
1>ClCompile:
1>  StdAfx.cpp
2>ClCompile:
2>  StdAfx.cpp
2>  gltfPackage.cpp
2>  glTF.cpp
2>  Warning static builds of getopt violate the Lesser GNU Public License
2>  getopt.cpp
2>  Warning static builds of getopt violate the Lesser GNU Public License
2>  Generating Code...
1>  dllmain.cpp
2>Link:
2>  glTF.vcxproj -> C:\glTF\FBX-glTF-master\FBX-glTF-master\x64\Debug\glTF.exe
2>cpprestsdk_AfterBuild:
2>  Creating hard link to copy "C:\glTF\FBX-glTF-master\FBX-glTF-master\packages\cpprestsdk.2.4.0.1\build\native....\license\websocketpp\COPYING" to "C:\glTF\FBX-glTF-master\FBX-glTF-master\x64\Debug\COPYING".
2>  Creating hard link to copy "C:\glTF\FBX-glTF-master\FBX-glTF-master\packages\cpprestsdk.2.4.0.1\build\native\bin\x64\v120\Debug\Desktop\cpprest120d_2_4.pdb" to "C:\glTF\FBX-glTF-master\FBX-glTF-master\x64\Debug\cpprest120d_2_4.pdb".
2>FinalizeBuildStatus:
2>  Deleting file "x64\Debug\glTF.tlog\unsuccessfulbuild".
2>  Touching "x64\Debug\glTF.tlog\glTF.lastbuildstate".
2>
2>Build succeeded.
2>
2>Time Elapsed 00:00:03.91
1>  JsonPrettify.cpp
1>  IOglTF.cpp
1>  gltfWriterVBO.cpp
1>  gltfWriter.cpp
1>  gltfWriter-Texture.cpp
1>  gltfWriter-Technique.cpp
1>  gltfWriter-Scene.cpp
1>  gltfWriter-Program.cpp
1>  gltfWriter-Null.cpp
1>  gltfWriter-Mesh.cpp
1>  gltfWriter-Material.cpp
1>  gltfWriter-Light.cpp
1>  gltfWriter-Camera.cpp
1>  gltfWriter-Buffer.cpp
1>  gltfWriter-Asset.cpp
1>  gltfWriter-Shaders.cpp
1>  gltfWriter-Line.cpp
1>  gltfReader.cpp
1>  glslShader.cpp
1>  Generating Code...
1>Link:
1>     Creating library C:\glTF\FBX-glTF-master\FBX-glTF-master\x64\Debug\IO-glTF.lib and object C:\glTF\FBX-glTF-master\FBX-glTF-master\x64\Debug\IO-glTF.exp
1>  IO-glTF.vcxproj -> C:\glTF\FBX-glTF-master\FBX-glTF-master\x64\Debug\IO-glTF.dll
1>FinalizeBuildStatus:
1>  Deleting file "x64\Debug\IO-glTF.tlog\unsuccessfulbuild".
1>  Touching "x64\Debug\IO-glTF.tlog\IO-glTF.lastbuildstate".
1>
1>Build succeeded.
1>
1>Time Elapsed 00:00:13.07
========== Rebuild All: 2 succeeded, 0 failed, 0 skipped ==========

**Comment by Cyperwu** [comment]
Hi Vijaya,

Seems there's something wrong with my computer so that I had it built in another one.

Deepest Thanks,
Cyper
